# permissions for end users to view bgpconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgpconfig-viewer-role
rules:
- apiGroups:
  - lb.lambdahj.site
  resources:
  - bgpconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lb.lambdahj.site
  resources:
  - bgpconfigs/status
  verbs:
  - get
