# permissions for end users to edit bgpconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgpconfig-editor-role
rules:
- apiGroups:
  - lb.lambdahj.site
  resources:
  - bgpconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lb.lambdahj.site
  resources:
  - bgpconfigs/status
  verbs:
  - get
