# permissions for end users to view bgpipsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgpipsconfig-viewer-role
rules:
- apiGroups:
  - lb.lambdahj.site
  resources:
  - bgpipsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lb.lambdahj.site
  resources:
  - bgpipsconfigs/status
  verbs:
  - get
